# Generated by Django 3.2.15 on 2024-04-25 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0003_rename_test_item_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='List',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
